[package]
name = "crafting"
version = "0.1.0"
edition = "2021"

[lib]
name = "crafting"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
atty = "0.2"
colored = "2.1"
