[package]
name = "mvp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mvp"
path = "src/main.rs"

[lib]
name = "mvp"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
